export const TIMES_PERSETS = {
  CLASSIC: 0,
  EXTENDED: 1,
  DEEP_WORK: 2,
  QUICK_SESSION: 3,
};

export const TIMES_PERSETS_LABELS = {
  [TIMES_PERSETS.CLASSIC]: "Classic",
  [TIMES_PERSETS.EXTENDED]: "Extended",
  [TIMES_PERSETS.DEEP_WORK]: "Deep Work",
  [TIMES_PERSETS.QUICK_SESSION]: "Quick Session",
};

export const TIMES_PRESETS_DESCRIPTIONS = {
  [TIMES_PERSETS.CLASSIC]: "25 min work, 5 min break",
  [TIMES_PERSETS.EXTENDED]: "50 min work, 10 min break",
  [TIMES_PERSETS.DEEP_WORK]: "90 min work, 15 min break",
  [TIMES_PERSETS.QUICK_SESSION]: "15 min work, 3 min break",
};

export const TIMES_PERSETS_DURATION = {
  [TIMES_PERSETS.CLASSIC]: 25,
  [TIMES_PERSETS.EXTENDED]: 50,
  [TIMES_PERSETS.DEEP_WORK]: 90,
  [TIMES_PERSETS.QUICK_SESSION]: 15,
};

export const TIMES_PRESETS_BREAK_DURATION = {
  [TIMES_PERSETS.CLASSIC]: 5,
  [TIMES_PERSETS.EXTENDED]: 10,
  [TIMES_PERSETS.DEEP_WORK]: 15,
  [TIMES_PERSETS.QUICK_SESSION]: 3,
};
